# Generated by Django 4.0 on 2021-12-17 10:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o2_level', models.IntegerField(max_length=3)),
                ('bp_level', models.IntegerField(max_length=3)),
                ('sugar_level', models.IntegerField(max_length=3)),
                ('date_monitored', models.DateTimeField(default=datetime.datetime(2021, 12, 17, 16, 23, 11, 248430))),
                ('past_medics', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
