# Generated by Django 4.0 on 2021-12-17 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='date_monitored',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 16, 27, 36, 695052)),
        ),
    ]
