# Generated by Django 4.0 on 2021-12-17 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_remove_health_user_health_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 17)),
        ),
    ]
