# Generated by Django 4.0 on 2021-12-17 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_health_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 17, 22, 24, 56, 831638)),
        ),
    ]
