# Generated by Django 4.0 on 2021-12-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_health_report_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health',
            old_name='past_medics',
            new_name='Feedback',
        ),
    ]
